Track to channel witch witch message is sent.
EHVAG/fancyauth pull request #16
Opened 2017-11-03 19:58 UTC by moritzuehling

2017-11-03 19:58 UTC, moritzuehling commented
Also, please merge #14 and then deploy after both are merged. 

Don't forget to redeploy to nuget, if we're on it :)

2017-11-04 00:46 UTC, main-- requested changes
With #14 merged, you could do this by joining to the last channel change event. If you insist on adding this to the ChatMessage, I feel like blindly taking the first target channel is rather questionable, especially since you don't even set it (xD).

2017-11-04 16:55 UTC, moritzuehling commented
Ooops, looks like I forgot to add that line. Problem is I often send messages to other channels, especially dank ones, and most of the time there is only one channel. 

I think this solution is honestly superior because it only adds information. However, we could add a `LogMessageChannel`-Table where we keep the many-to-many relationship, or alternatively simply set the flag if a message was sent to subchannels, and save the highest channel

That would cover both usecases and would only fall apart when re-arranging channels.

2017-11-04 20:55 UTC, main-- commented
Oh and I forgot to mention that any schema change always needs a migration so good luck with that. Also, you forgot to `await`.

---

>most of the time there is only one channel.

In reality, this is mostly bad modelling by the murmur API - you can only send messages to either a single user or a single channel (or a single subtree of channels, but fancyauth ignores those anyway right now because no one ever uses them). So you may convince me to rely on these assumptions, but please add a comment that explains what's going on.

2025-04-07 14:16 UTC, closed without merging